// <auto-generated />
using System;
using FribergCarRentals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FribergCarRentals.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FribergCarRentals.Models.CarEntity", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int>("PropulsionSystemVehiclePropulsionId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RentalStatusCarRentalStatusId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("PropulsionSystemVehiclePropulsionId");

                    b.HasIndex("RentalStatusCarRentalStatusId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarRentalStatusEntity", b =>
                {
                    b.Property<int>("CarRentalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarRentalStatusId");

                    b.ToTable("CarRentalStatuses");

                    b.HasData(
                        new
                        {
                            CarRentalStatusId = 1,
                            StatusDescription = "Not available for renting",
                            StatusName = "Unavailable"
                        },
                        new
                        {
                            CarRentalStatusId = 2,
                            StatusDescription = "Available for renting",
                            StatusName = "Available"
                        },
                        new
                        {
                            CarRentalStatusId = 3,
                            StatusDescription = "Already rented",
                            StatusName = "Rented"
                        },
                        new
                        {
                            CarRentalStatusId = 4,
                            StatusDescription = "Taken out of service permanently",
                            StatusName = "OutOfService"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.Models.ImageEntity", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("CarEntityCarId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("CarEntityCarId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FribergCarRentals.Models.VehiclePropulsionEntity", b =>
                {
                    b.Property<int>("VehiclePropulsionId")
                        .HasColumnType("int");

                    b.Property<string>("PropulsionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropulsionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehiclePropulsionId");

                    b.ToTable("VehiclePropulsion");

                    b.HasData(
                        new
                        {
                            VehiclePropulsionId = 1,
                            PropulsionDescription = "No propulsion system.",
                            PropulsionName = "None"
                        },
                        new
                        {
                            VehiclePropulsionId = 2,
                            PropulsionDescription = "Other type of vehicle.",
                            PropulsionName = "Other"
                        },
                        new
                        {
                            VehiclePropulsionId = 3,
                            PropulsionDescription = "Battery electric vehicle.",
                            PropulsionName = "BEV"
                        },
                        new
                        {
                            VehiclePropulsionId = 4,
                            PropulsionDescription = "Diesel powered vehicle.",
                            PropulsionName = "Diesel"
                        },
                        new
                        {
                            VehiclePropulsionId = 5,
                            PropulsionDescription = "Gasoline powered vehicle.",
                            PropulsionName = "Gasoline"
                        },
                        new
                        {
                            VehiclePropulsionId = 7,
                            PropulsionDescription = "Plugin-in hybrid electric vehicle.",
                            PropulsionName = "PHEV"
                        },
                        new
                        {
                            VehiclePropulsionId = 9,
                            PropulsionDescription = "Hybrid electric vehicle.",
                            PropulsionName = "HEV"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarEntity", b =>
                {
                    b.HasOne("FribergCarRentals.Models.VehiclePropulsionEntity", "PropulsionSystem")
                        .WithMany()
                        .HasForeignKey("PropulsionSystemVehiclePropulsionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergCarRentals.Models.CarRentalStatusEntity", "RentalStatus")
                        .WithMany()
                        .HasForeignKey("RentalStatusCarRentalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropulsionSystem");

                    b.Navigation("RentalStatus");
                });

            modelBuilder.Entity("FribergCarRentals.Models.ImageEntity", b =>
                {
                    b.HasOne("FribergCarRentals.Models.CarEntity", null)
                        .WithMany("Images")
                        .HasForeignKey("CarEntityCarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarEntity", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
