// <auto-generated />
using System;
using FribergCarRentals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FribergCarRentals.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.AdminEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.CarBookingEntity", b =>
                {
                    b.Property<int>("CarBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarBookingId"));

                    b.Property<int>("BookingStatusCarBookingStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CarOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RentalCostPerDay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ReturnDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CarBookingId");

                    b.HasIndex("BookingStatusCarBookingStatusId");

                    b.HasIndex("CarId");

                    b.HasIndex("CarOrderId");

                    b.ToTable("CarBookings");
                });

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.CarBookingStatusEntity", b =>
                {
                    b.Property<int>("CarBookingStatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarBookingStatusId");

                    b.ToTable("CarBookingStatuses");

                    b.HasData(
                        new
                        {
                            CarBookingStatusId = 1,
                            StatusDescription = "No status.",
                            StatusName = "None"
                        },
                        new
                        {
                            CarBookingStatusId = 2,
                            StatusDescription = "Pending status.",
                            StatusName = "Pending"
                        },
                        new
                        {
                            CarBookingStatusId = 3,
                            StatusDescription = "Car is picked up.",
                            StatusName = "PickedUpCar"
                        },
                        new
                        {
                            CarBookingStatusId = 4,
                            StatusDescription = "Car is returned.",
                            StatusName = "ReturnedCar"
                        },
                        new
                        {
                            CarBookingStatusId = 5,
                            StatusDescription = "Booking is canceled.",
                            StatusName = "Canceled"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.OrderStatusEntity", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            StatusDescription = "No order status.",
                            StatusName = "None"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            StatusDescription = "Order is created.",
                            StatusName = "Created"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            StatusDescription = "Order is completed.",
                            StatusName = "Completed"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            StatusDescription = "Order is canceled.",
                            StatusName = "Canceled"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.UserRoleEntity", b =>
                {
                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserRoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 0,
                            UserRoleDescription = "No role.",
                            UserRoleName = "None"
                        },
                        new
                        {
                            UserRoleId = 1,
                            UserRoleDescription = "Admin role.",
                            UserRoleName = "Admin"
                        },
                        new
                        {
                            UserRoleId = 2,
                            UserRoleDescription = "Customer role.",
                            UserRoleName = "Customer"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarEntity", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int>("PropulsionSystemVehiclePropulsionId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalCostPerDay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RentalStatusCarRentalStatusId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("PropulsionSystemVehiclePropulsionId");

                    b.HasIndex("RentalStatusCarRentalStatusId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarOrderEntity", b =>
                {
                    b.Property<int>("CarOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarOrderId"));

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.HasKey("CarOrderId");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("CarOrders");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarRentalStatusEntity", b =>
                {
                    b.Property<int>("CarRentalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarRentalStatusId");

                    b.ToTable("CarRentalStatuses");

                    b.HasData(
                        new
                        {
                            CarRentalStatusId = 1,
                            StatusDescription = "Not available for renting",
                            StatusName = "Unavailable"
                        },
                        new
                        {
                            CarRentalStatusId = 2,
                            StatusDescription = "Available for renting",
                            StatusName = "Available"
                        },
                        new
                        {
                            CarRentalStatusId = 3,
                            StatusDescription = "Already rented",
                            StatusName = "Rented"
                        },
                        new
                        {
                            CarRentalStatusId = 4,
                            StatusDescription = "Taken out of service permanently",
                            StatusName = "OutOfService"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.Models.CustomerEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FribergCarRentals.Models.ImageEntity", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("CarEntityCarId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("CarEntityCarId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FribergCarRentals.Models.PaymentEntity", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("OrderCarOrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderCarOrderId");

                    b.ToTable("PaymentEntity");
                });

            modelBuilder.Entity("FribergCarRentals.Models.VehiclePropulsionEntity", b =>
                {
                    b.Property<int>("VehiclePropulsionId")
                        .HasColumnType("int");

                    b.Property<string>("PropulsionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropulsionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehiclePropulsionId");

                    b.ToTable("VehiclePropulsion");

                    b.HasData(
                        new
                        {
                            VehiclePropulsionId = 1,
                            PropulsionDescription = "No propulsion system.",
                            PropulsionName = "None"
                        },
                        new
                        {
                            VehiclePropulsionId = 2,
                            PropulsionDescription = "Other type of vehicle.",
                            PropulsionName = "Other"
                        },
                        new
                        {
                            VehiclePropulsionId = 3,
                            PropulsionDescription = "Battery electric vehicle.",
                            PropulsionName = "BEV"
                        },
                        new
                        {
                            VehiclePropulsionId = 4,
                            PropulsionDescription = "Diesel powered vehicle.",
                            PropulsionName = "Diesel"
                        },
                        new
                        {
                            VehiclePropulsionId = 5,
                            PropulsionDescription = "Gasoline powered vehicle.",
                            PropulsionName = "Gasoline"
                        },
                        new
                        {
                            VehiclePropulsionId = 7,
                            PropulsionDescription = "Plugin-in hybrid electric vehicle.",
                            PropulsionName = "PHEV"
                        },
                        new
                        {
                            VehiclePropulsionId = 9,
                            PropulsionDescription = "Hybrid electric vehicle.",
                            PropulsionName = "HEV"
                        });
                });

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.AdminEntity", b =>
                {
                    b.HasOne("FribergCarRentals.DataAccess.EntityClasses.UserRoleEntity", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("FribergCarRentals.DataAccess.EntityClasses.CarBookingEntity", b =>
                {
                    b.HasOne("FribergCarRentals.DataAccess.EntityClasses.CarBookingStatusEntity", "BookingStatus")
                        .WithMany()
                        .HasForeignKey("BookingStatusCarBookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergCarRentals.Models.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergCarRentals.Models.CarOrderEntity", "CarOrder")
                        .WithMany("CarBookings")
                        .HasForeignKey("CarOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Car");

                    b.Navigation("CarOrder");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarEntity", b =>
                {
                    b.HasOne("FribergCarRentals.Models.VehiclePropulsionEntity", "PropulsionSystem")
                        .WithMany()
                        .HasForeignKey("PropulsionSystemVehiclePropulsionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergCarRentals.Models.CarRentalStatusEntity", "RentalStatus")
                        .WithMany()
                        .HasForeignKey("RentalStatusCarRentalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropulsionSystem");

                    b.Navigation("RentalStatus");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarOrderEntity", b =>
                {
                    b.HasOne("FribergCarRentals.Models.CustomerEntity", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FribergCarRentals.DataAccess.EntityClasses.OrderStatusEntity", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CustomerEntity", b =>
                {
                    b.HasOne("FribergCarRentals.DataAccess.EntityClasses.UserRoleEntity", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("FribergCarRentals.Models.ImageEntity", b =>
                {
                    b.HasOne("FribergCarRentals.Models.CarEntity", null)
                        .WithMany("Images")
                        .HasForeignKey("CarEntityCarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FribergCarRentals.Models.PaymentEntity", b =>
                {
                    b.HasOne("FribergCarRentals.Models.CarOrderEntity", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderCarOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CarOrderEntity", b =>
                {
                    b.Navigation("CarBookings");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FribergCarRentals.Models.CustomerEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
